export const gamesList = [
  "BGMI",
  "Call of Duty: Mobile",
  "Free Fire",
  "Apex Legends Mobile",
  "Genshin Impact",
  "PUBG: New State",
  "Minecraft",
  "Among Us",
  "Roblox",
  "Clash of Clans",
  "Candy Crush Saga",
  "Subway Surfers",
  "Temple Run",
  "Pokémon GO",
  "Garena Free Fire MAX",
  "Ludo King",
  "Asphalt 9: Legends",
  "8 Ball Pool",
  "Clash Royale",
  "Brawl Stars",
  "FIFA Mobile",
  "PUBG Mobile",
  "Fortnite",
  "League of Legends: Wild Rift",
  "Call of Duty: Warzone Mobile",
  "Valorant Mobile",
  "Diablo Immortal",
  "Honkai: Star Rail",
  "Greedfall",
  "FIFA",
]

